# Generated by Django 3.0.8 on 2021-12-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211214_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='cart.CategoryVariation'),
        ),
    ]
